defmodule ExEuler.Problem002 do
  require Integer

  @moduledoc """
  Problem 2: Even Fibonacci numbers

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  """

  @limit 4_000_000

  @doc """
  iex> ExEuler.Problem002.solve
  4613732
  """
  def solve do
    fib(0, 0, 1)
  end

  def fib(r, _p, _n) when r >= @limit, do: r

  def fib(r, p, n) when Integer.is_even(p), do: fib(r + p, n, p + n)
  def fib(r, p, n), do: fib(r, n, p + n)
end
